# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - GroupeJR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_5ba4bfb29fac4f80a2ba2ae134d0f682 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_01b886c4d63947349522b8c357c1dff6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_5ba4bfb29fac4f80a2ba2ae134d0f682 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'GroupeJR'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9881587378ec4ad48fbf37881139ce80 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_5ba4bfb29fac4f80a2ba2ae134d0f682 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'